def CAPCITY(cc):
    print("DODGE VIPER  STR-10 DEMON HAS A ",cc,"V10 ENGINE")
CAPCITY("8400cc/8.4L")
def ENGINE():
    print("GTR R34 NISMO V-SEC Z-TUNE HAS A TUNED VERSION OF THE ",IDK)
IDK="RB26DETT"
ENGINE()