def ENGINES():
    print("GTR R35 HAS A VR38 DETT")
    print("GTR R34 HAS A RB26 DETT") 
    print("SUPRA MK4 HAS A 2JZ-GTE") 
    print("DODGE VIPER SRT-10 DEMON HAS A 8,400CC V10")  
ENGINES()
IDK=input("DO YOU AGREE ON THIS INFORMATION???")
